[package]
name = "string-tree"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
rand = "0.9.1"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
smallvec = "1.15.1"
